# Generated by Django 6.0.4 on 2026-04-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Título (Opcional)')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Subtítulo (Opcional)')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Imagen Landscape')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
            ],
            options={
                'verbose_name': 'Imagen de Carrusel',
                'verbose_name_plural': 'Imágenes de Carrusel',
                'ordering': ['order'],
            },
        ),
    ]
